export const SEARCH_START = 'SEARCH/SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH/SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH/SEARCH_FAILURE';
export const LOAD_MORE_START = 'SEARCH/LOAD_MORE_START';
export const LOAD_MORE_SUCCESS = 'SEARCH/LOAD_MORE_SUCCESS';
export const LOAD_MORE_FAILURE = 'SEARCH/LOAD_MORE_FAILURE';
