export const LOAD_CONTACTS_START = 'CONTACTS/LOAD_CONTACTS_START';
export const LOAD_CONTACTS_SUCCESS = 'CONTACTS/LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_FAILURE = 'CONTACTS/LOAD_CONTACTS_FAILURE';
export const SET_PERMISSIONS_GRANTED = 'CONTACTS/SET_PERMISSIONS_GRANTED';
